### User

GET http://localhost:8080/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhcnJhc2ZhanJpQGdtYWlsLmNvbSIsImV4cCI6MTc2NTM0ODYyOCwicm9sZSI6ImFkbWluIiwidXNlcl9pZCI6MjB9.2iT6KHHN7FC7QJaEwfjKTlbA0NpBDSDrYqpT3cG3mXU


### logOut

POST http://localhost:8080/api/auth/admin/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhcnJhc2ZhanJpQGdtYWlsLmNvbSIsImV4cCI6MTc2NTM0ODQ2Niwicm9sZSI6ImFkbWluIiwidXNlcl9pZCI6MjB9.e5Hz-qKI7EGglHwVFDjwcMkbxY3KeC6pzND_KUpWpwQ